"""hotel_table

Revision ID: 438618468dd6
Revises: 769fa6a825f1
Create Date: 2022-10-18 20:16:12.052688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '438618468dd6'
down_revision = '769fa6a825f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hotel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hotel_name', sa.String(length=64), nullable=True),
    sa.Column('hotel_link', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hotel_hotel_name'), 'hotel', ['hotel_name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hotel_hotel_name'), table_name='hotel')
    op.drop_table('hotel')
    # ### end Alembic commands ###
